### ISSUE TITLE
Question about your username

### ISSUE THREAD

**Issue by jnnkls** [jani/irssi#1]
Hi Jan,
I'm sorry to open an issue here that has nothing to do with your repository. My name is Jan-Niklas and I'm using Github under the name "JaniDJ" since 2013. The name was intended as a stopgap. You have to know that everyone who knows me knows me under the name "Jani" as an abbreviation for my name. Due to my current job and my studying I have to and want to use GitHub more intensively. I don't know how actively you use your GitHub account, but if there is a possibility that you could release your username, that would be amazing. However, I totally understand if you want to keep your username. 
Thank you for your time!
With best regards, Jani

**Comment by jnnkls** [comment]
Hi @jani, I would really appreciate an answer ;)

**Comment by jani** [comment]
Hi, well, I’ve been using my nickname for a bit longer, so no, sorry.
